name: Deploy to Test

on:
  push:
    branches: 
      - 'main'
jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: 
        name: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: ${{ github.ref }}
          check-name: 'laravel-tests'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Fake Deploy
        run: echo "Deployed to Test!"
